version: '2.4'
services:
  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python manage.py runserver 0.0.0.0:8000'
    env_file:
      - envs/dev.env
    stdin_open: true
    tty: true
    volumes:
      - '.:/app'
    ports:
      - '8000:8000'
      - '5678:5678'
    depends_on:
      - db
      - rabbitmq
      - celery_worker
  db:
    image: 'postgres:11'
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data:/var/lib/postgresql/data/'
  # Rabbit MQ message broker
  rabbitmq:
    image: rabbitmq:3.8.3-alpine
  # worker for celery
  celery_worker:
    <<: *web
    command: celery -A config worker --loglevel=info
    ports: []
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
