# Generated by Django 2.2.6 on 2020-03-28 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracking.IssueTypes'),
        ),
        migrations.AlterField(
            model_name='issuetypes',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracking.Project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category_id',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.CreateModel(
            name='IssueImages',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('content', models.URLField()),
                ('thumbnail', models.URLField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_tracking.Issue')),
            ],
        ),
    ]
