# Generated by Django 2.2.6 on 2020-03-08 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_type_id',
            new_name='issue_type',
        ),
        migrations.RenameField(
            model_name='issue',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='issuetypes',
            old_name='project_id',
            new_name='project',
        ),
    ]
