# Generated by Django 2.2.6 on 2020-03-31 19:05

from django.db import migrations
import prosemirror.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracking', '0002_auto_20200328_0423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=prosemirror.fields.ProseMirrorField(blank=True, null=True),
        ),
    ]
