# Generated by Django 2.2.6 on 2020-08-04 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_tracking', '0002_auto_20200328_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='issueimages',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='Screenshot'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
